ALTER TABLE "Project" ADD COLUMN "referenceImageCount" INTEGER NOT NULL DEFAULT 6;
ALTER TABLE "Project" ADD COLUMN "referenceVideoCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Project" ADD COLUMN "referenceAudioCount" INTEGER NOT NULL DEFAULT 0;
